server:
  port: 55555

spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${hrsys.datasource.host}:${hrsys.datasource.port}/hrsys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: ${hrsys.datasource.username}
      password: ${hrsys.datasource.password}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: hrsys
  ttl: 7200000  # 1000*60*60*2
  token-name: token

minio:
  # MinIO服务器地址
  endpoint: ${minio.endpoint}
  # MinIO服务器访问凭据
  accessKey: ${minio.accessKey}
  secretKey: ${minio.secretKey}
  # MinIO桶名称
  bucket: hrsys

